"""initial migration

Revision ID: f80f27256588
Revises: 
Create Date: 2023-01-17 15:11:49.916878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f80f27256588'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customers',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('GivenName', sa.String(length=50), nullable=False),
    sa.Column('Surname', sa.String(length=50), nullable=False),
    sa.Column('Streetaddress', sa.String(length=50), nullable=False),
    sa.Column('City', sa.String(length=50), nullable=False),
    sa.Column('Zipcode', sa.String(length=10), nullable=False),
    sa.Column('Country', sa.String(length=30), nullable=False),
    sa.Column('CountryCode', sa.String(length=2), nullable=False),
    sa.Column('Birthday', sa.DateTime(), nullable=False),
    sa.Column('NationalId', sa.String(length=20), nullable=False),
    sa.Column('TelephoneCountryCode', sa.Integer(), nullable=False),
    sa.Column('Telephone', sa.String(length=20), nullable=False),
    sa.Column('EmailAddress', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Role',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Accounts',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AccountType', sa.String(length=10), nullable=False),
    sa.Column('Created', sa.DateTime(), nullable=False),
    sa.Column('Balance', sa.Integer(), nullable=False),
    sa.Column('CustomerId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerId'], ['Customers.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Users',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('EmailAddress', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=20), nullable=False),
    sa.Column('GivenName', sa.String(length=50), nullable=False),
    sa.Column('Surname', sa.String(length=50), nullable=False),
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RoleId'], ['Role.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Transactions',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=20), nullable=False),
    sa.Column('Operation', sa.String(length=50), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Amount', sa.Integer(), nullable=False),
    sa.Column('NewBalance', sa.Integer(), nullable=False),
    sa.Column('AccountId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AccountId'], ['Accounts.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('role')
    op.drop_table('transactions')
    op.drop_table('customers')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('EmailAddress', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Password', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('GivenName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Surname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('RoleId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['RoleId'], ['role.Id'], name='users_ibfk_1'),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('accounts',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('AccountType', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('Created', mysql.DATETIME(), nullable=False),
    sa.Column('Balance', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('CustomerId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['CustomerId'], ['customers.Id'], name='accounts_ibfk_1'),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customers',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('GivenName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Surname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Streetaddress', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('City', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Zipcode', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('Country', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('CountryCode', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('Birthday', mysql.DATETIME(), nullable=False),
    sa.Column('NationalId', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('TelephoneCountryCode', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Telephone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('EmailAddress', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('transactions',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Operation', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Date', mysql.DATETIME(), nullable=False),
    sa.Column('Amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('NewBalance', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('AccountId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['AccountId'], ['accounts.Id'], name='transactions_ibfk_1'),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Role', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Transactions')
    op.drop_table('Users')
    op.drop_table('Accounts')
    op.drop_table('Role')
    op.drop_table('Customers')
    # ### end Alembic commands ###
